/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * Kanban Board API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Card,
  CreateCardRequest,
  ErrorResponse,
  UpdateCardRequest,
} from '../models/index';
import {
    CardFromJSON,
    CardToJSON,
    CreateCardRequestFromJSON,
    CreateCardRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    UpdateCardRequestFromJSON,
    UpdateCardRequestToJSON,
} from '../models/index';

export interface CreateCardOperationRequest {
    createCardRequest: CreateCardRequest;
}

export interface DeleteCardByIdRequest {
    id: number;
}

export interface GetCardByIdRequest {
    id: number;
}

export interface UpdateCardOperationRequest {
    id: number;
    updateCardRequest: UpdateCardRequest;
}

/**
 * 
 */
export class CardApi extends runtime.BaseAPI {

    /**
     * Creates request options for createCard without sending the request
     */
    async createCardRequestOpts(requestParameters: CreateCardOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createCardRequest'] == null) {
            throw new runtime.RequiredError(
                'createCardRequest',
                'Required parameter "createCardRequest" was null or undefined when calling createCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/card`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCardRequestToJSON(requestParameters['createCardRequest']),
        };
    }

    /**
     * Create new card
     */
    async createCardRaw(requestParameters: CreateCardOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Card>> {
        const requestOptions = await this.createCardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardFromJSON(jsonValue));
    }

    /**
     * Create new card
     */
    async createCard(requestParameters: CreateCardOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Card> {
        const response = await this.createCardRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteCardById without sending the request
     */
    async deleteCardByIdRequestOpts(requestParameters: DeleteCardByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteCardById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/card/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete card
     */
    async deleteCardByIdRaw(requestParameters: DeleteCardByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteCardByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete card
     */
    async deleteCardById(requestParameters: DeleteCardByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteCardByIdRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getCardById without sending the request
     */
    async getCardByIdRequestOpts(requestParameters: GetCardByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCardById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/card/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get card by ID
     */
    async getCardByIdRaw(requestParameters: GetCardByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Card>> {
        const requestOptions = await this.getCardByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardFromJSON(jsonValue));
    }

    /**
     * Get card by ID
     */
    async getCardById(requestParameters: GetCardByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Card> {
        const response = await this.getCardByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateCard without sending the request
     */
    async updateCardRequestOpts(requestParameters: UpdateCardOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateCard().'
            );
        }

        if (requestParameters['updateCardRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCardRequest',
                'Required parameter "updateCardRequest" was null or undefined when calling updateCard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/card/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCardRequestToJSON(requestParameters['updateCardRequest']),
        };
    }

    /**
     * Update card
     */
    async updateCardRaw(requestParameters: UpdateCardOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Card>> {
        const requestOptions = await this.updateCardRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CardFromJSON(jsonValue));
    }

    /**
     * Update card
     */
    async updateCard(requestParameters: UpdateCardOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Card> {
        const response = await this.updateCardRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
