/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * Kanban Board API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ColumnResponse,
  CreateColumnRequest,
  ErrorResponse,
  UpdateColumnRequest,
} from '../models/index';
import {
    ColumnResponseFromJSON,
    ColumnResponseToJSON,
    CreateColumnRequestFromJSON,
    CreateColumnRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    UpdateColumnRequestFromJSON,
    UpdateColumnRequestToJSON,
} from '../models/index';

export interface CreateColumnOperationRequest {
    createColumnRequest: CreateColumnRequest;
}

export interface DeleteColumnByIdRequest {
    id: number;
}

export interface GetColumnByIdRequest {
    id: number;
}

export interface UpdateColumnOperationRequest {
    id: number;
    updateColumnRequest: UpdateColumnRequest;
}

/**
 * 
 */
export class ColumnApi extends runtime.BaseAPI {

    /**
     * Creates request options for createColumn without sending the request
     */
    async createColumnRequestOpts(requestParameters: CreateColumnOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createColumnRequest'] == null) {
            throw new runtime.RequiredError(
                'createColumnRequest',
                'Required parameter "createColumnRequest" was null or undefined when calling createColumn().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/column`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateColumnRequestToJSON(requestParameters['createColumnRequest']),
        };
    }

    /**
     * Create new column
     */
    async createColumnRaw(requestParameters: CreateColumnOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ColumnResponse>> {
        const requestOptions = await this.createColumnRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ColumnResponseFromJSON(jsonValue));
    }

    /**
     * Create new column
     */
    async createColumn(requestParameters: CreateColumnOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ColumnResponse> {
        const response = await this.createColumnRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteColumnById without sending the request
     */
    async deleteColumnByIdRequestOpts(requestParameters: DeleteColumnByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteColumnById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/column/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete column
     */
    async deleteColumnByIdRaw(requestParameters: DeleteColumnByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteColumnByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete column
     */
    async deleteColumnById(requestParameters: DeleteColumnByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteColumnByIdRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAllColumns without sending the request
     */
    async getAllColumnsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/column`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get all columns
     */
    async getAllColumnsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ColumnResponse>>> {
        const requestOptions = await this.getAllColumnsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ColumnResponseFromJSON));
    }

    /**
     * Get all columns
     */
    async getAllColumns(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ColumnResponse>> {
        const response = await this.getAllColumnsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getColumnById without sending the request
     */
    async getColumnByIdRequestOpts(requestParameters: GetColumnByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getColumnById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/column/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get column by ID
     */
    async getColumnByIdRaw(requestParameters: GetColumnByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ColumnResponse>> {
        const requestOptions = await this.getColumnByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ColumnResponseFromJSON(jsonValue));
    }

    /**
     * Get column by ID
     */
    async getColumnById(requestParameters: GetColumnByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ColumnResponse> {
        const response = await this.getColumnByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateColumn without sending the request
     */
    async updateColumnRequestOpts(requestParameters: UpdateColumnOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateColumn().'
            );
        }

        if (requestParameters['updateColumnRequest'] == null) {
            throw new runtime.RequiredError(
                'updateColumnRequest',
                'Required parameter "updateColumnRequest" was null or undefined when calling updateColumn().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/column/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateColumnRequestToJSON(requestParameters['updateColumnRequest']),
        };
    }

    /**
     * Update column
     */
    async updateColumnRaw(requestParameters: UpdateColumnOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ColumnResponse>> {
        const requestOptions = await this.updateColumnRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ColumnResponseFromJSON(jsonValue));
    }

    /**
     * Update column
     */
    async updateColumn(requestParameters: UpdateColumnOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ColumnResponse> {
        const response = await this.updateColumnRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
