/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * Kanban Board API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  Me200Response,
  UpdatePasswordRequest,
  UpdatePersonalDataRequest,
  UpdateUsernameRequest,
  UserResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    Me200ResponseFromJSON,
    Me200ResponseToJSON,
    UpdatePasswordRequestFromJSON,
    UpdatePasswordRequestToJSON,
    UpdatePersonalDataRequestFromJSON,
    UpdatePersonalDataRequestToJSON,
    UpdateUsernameRequestFromJSON,
    UpdateUsernameRequestToJSON,
    UserResponseFromJSON,
    UserResponseToJSON,
} from '../models/index';

export interface DeleteUserByIdRequest {
    userId: number;
}

export interface UpdatePasswordOperationRequest {
    updatePasswordRequest: UpdatePasswordRequest;
}

export interface UpdatePersonalDataOperationRequest {
    updatePersonalDataRequest: UpdatePersonalDataRequest;
}

export interface UpdateUsernameOperationRequest {
    updateUsernameRequest: UpdateUsernameRequest;
}

/**
 * 
 */
export class UserApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteUserById without sending the request
     */
    async deleteUserByIdRequestOpts(requestParameters: DeleteUserByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling deleteUserById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/user/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a user by ID
     */
    async deleteUserByIdRaw(requestParameters: DeleteUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteUserByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a user by ID
     */
    async deleteUserById(requestParameters: DeleteUserByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteUserByIdRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for me without sending the request
     */
    async meRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/user/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get current user info from JWT token
     */
    async meRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Me200Response>> {
        const requestOptions = await this.meRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Me200ResponseFromJSON(jsonValue));
    }

    /**
     * Get current user info from JWT token
     */
    async me(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Me200Response> {
        const response = await this.meRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updatePassword without sending the request
     */
    async updatePasswordRequestOpts(requestParameters: UpdatePasswordOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updatePasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'updatePasswordRequest',
                'Required parameter "updatePasswordRequest" was null or undefined when calling updatePassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/update-password`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePasswordRequestToJSON(requestParameters['updatePasswordRequest']),
        };
    }

    /**
     * Update password
     */
    async updatePasswordRaw(requestParameters: UpdatePasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.updatePasswordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Update password
     */
    async updatePassword(requestParameters: UpdatePasswordOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.updatePasswordRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updatePersonalData without sending the request
     */
    async updatePersonalDataRequestOpts(requestParameters: UpdatePersonalDataOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updatePersonalDataRequest'] == null) {
            throw new runtime.RequiredError(
                'updatePersonalDataRequest',
                'Required parameter "updatePersonalDataRequest" was null or undefined when calling updatePersonalData().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/personal-data`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePersonalDataRequestToJSON(requestParameters['updatePersonalDataRequest']),
        };
    }

    /**
     * Update personal data
     */
    async updatePersonalDataRaw(requestParameters: UpdatePersonalDataOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        const requestOptions = await this.updatePersonalDataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Update personal data
     */
    async updatePersonalData(requestParameters: UpdatePersonalDataOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.updatePersonalDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateUsername without sending the request
     */
    async updateUsernameRequestOpts(requestParameters: UpdateUsernameOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['updateUsernameRequest'] == null) {
            throw new runtime.RequiredError(
                'updateUsernameRequest',
                'Required parameter "updateUsernameRequest" was null or undefined when calling updateUsername().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/user-data`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateUsernameRequestToJSON(requestParameters['updateUsernameRequest']),
        };
    }

    /**
     * Update username
     */
    async updateUsernameRaw(requestParameters: UpdateUsernameOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserResponse>> {
        const requestOptions = await this.updateUsernameRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserResponseFromJSON(jsonValue));
    }

    /**
     * Update username
     */
    async updateUsername(requestParameters: UpdateUsernameOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserResponse> {
        const response = await this.updateUsernameRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
