/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardRequest
 */
export interface CardRequest {
    /**
     * 
     * @type {string}
     * @memberof CardRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CardRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CardRequest
     */
    assignedTo: number;
    /**
     * 
     * @type {number}
     * @memberof CardRequest
     */
    columnId: number;
}

/**
 * Check if a given object implements the CardRequest interface.
 */
export function instanceOfCardRequest(value: object): value is CardRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('assignedTo' in value) || value['assignedTo'] === undefined) return false;
    if (!('columnId' in value) || value['columnId'] === undefined) return false;
    return true;
}

export function CardRequestFromJSON(json: any): CardRequest {
    return CardRequestFromJSONTyped(json, false);
}

export function CardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'assignedTo': json['assignedTo'],
        'columnId': json['columnId'],
    };
}

export function CardRequestToJSON(json: any): CardRequest {
    return CardRequestToJSONTyped(json, false);
}

export function CardRequestToJSONTyped(value?: CardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'assignedTo': value['assignedTo'],
        'columnId': value['columnId'],
    };
}

