/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CardResponse
 */
export interface CardResponse {
    /**
     * 
     * @type {number}
     * @memberof CardResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CardResponse
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof CardResponse
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CardResponse
     */
    assignedTo?: number;
    /**
     * 
     * @type {number}
     * @memberof CardResponse
     */
    columnId?: number;
}

/**
 * Check if a given object implements the CardResponse interface.
 */
export function instanceOfCardResponse(value: object): value is CardResponse {
    return true;
}

export function CardResponseFromJSON(json: any): CardResponse {
    return CardResponseFromJSONTyped(json, false);
}

export function CardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'assignedTo': json['assignedTo'] == null ? undefined : json['assignedTo'],
        'columnId': json['columnId'] == null ? undefined : json['columnId'],
    };
}

export function CardResponseToJSON(json: any): CardResponse {
    return CardResponseToJSONTyped(json, false);
}

export function CardResponseToJSONTyped(value?: CardResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'assignedTo': value['assignedTo'],
        'columnId': value['columnId'],
    };
}

