/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * Kanban Board API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Card } from './Card';
import {
    CardFromJSON,
    CardFromJSONTyped,
    CardToJSON,
    CardToJSONTyped,
} from './Card';

/**
 * 
 * @export
 * @interface ColumnResponse
 */
export interface ColumnResponse {
    /**
     * 
     * @type {number}
     * @memberof ColumnResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ColumnResponse
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof ColumnResponse
     */
    position?: number;
    /**
     * 
     * @type {Array<Card>}
     * @memberof ColumnResponse
     */
    cards?: Array<Card>;
    /**
     * 
     * @type {number}
     * @memberof ColumnResponse
     */
    projectId?: number;
}

/**
 * Check if a given object implements the ColumnResponse interface.
 */
export function instanceOfColumnResponse(value: object): value is ColumnResponse {
    return true;
}

export function ColumnResponseFromJSON(json: any): ColumnResponse {
    return ColumnResponseFromJSONTyped(json, false);
}

export function ColumnResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'position': json['position'] == null ? undefined : json['position'],
        'cards': json['cards'] == null ? undefined : ((json['cards'] as Array<any>).map(CardFromJSON)),
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
    };
}

export function ColumnResponseToJSON(json: any): ColumnResponse {
    return ColumnResponseToJSONTyped(json, false);
}

export function ColumnResponseToJSONTyped(value?: ColumnResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'position': value['position'],
        'cards': value['cards'] == null ? undefined : ((value['cards'] as Array<any>).map(CardToJSON)),
        'projectId': value['projectId'],
    };
}

