/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ColumnRequest
 */
export interface ColumnRequest {
    /**
     * 
     * @type {string}
     * @memberof ColumnRequest
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof ColumnRequest
     */
    position: number;
    /**
     * 
     * @type {number}
     * @memberof ColumnRequest
     */
    projectId: number;
}

/**
 * Check if a given object implements the ColumnRequest interface.
 */
export function instanceOfColumnRequest(value: object): value is ColumnRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    if (!('projectId' in value) || value['projectId'] === undefined) return false;
    return true;
}

export function ColumnRequestFromJSON(json: any): ColumnRequest {
    return ColumnRequestFromJSONTyped(json, false);
}

export function ColumnRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ColumnRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'position': json['position'],
        'projectId': json['projectId'],
    };
}

export function ColumnRequestToJSON(json: any): ColumnRequest {
    return ColumnRequestToJSONTyped(json, false);
}

export function ColumnRequestToJSONTyped(value?: ColumnRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'position': value['position'],
        'projectId': value['projectId'],
    };
}

