/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * Kanban Board API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateColumnRequest
 */
export interface CreateColumnRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateColumnRequest
     */
    title: string;
    /**
     * 
     * @type {number}
     * @memberof CreateColumnRequest
     */
    position: number;
    /**
     * 
     * @type {number}
     * @memberof CreateColumnRequest
     */
    projectId?: number;
}

/**
 * Check if a given object implements the CreateColumnRequest interface.
 */
export function instanceOfCreateColumnRequest(value: object): value is CreateColumnRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    return true;
}

export function CreateColumnRequestFromJSON(json: any): CreateColumnRequest {
    return CreateColumnRequestFromJSONTyped(json, false);
}

export function CreateColumnRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateColumnRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'position': json['position'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
    };
}

export function CreateColumnRequestToJSON(json: any): CreateColumnRequest {
    return CreateColumnRequestToJSONTyped(json, false);
}

export function CreateColumnRequestToJSONTyped(value?: CreateColumnRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'position': value['position'],
        'projectId': value['projectId'],
    };
}

