/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * Kanban Board API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateCardRequest
 */
export interface CreateCardRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateCardRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateCardRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCardRequest
     */
    assignedToId?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCardRequest
     */
    columnId: number;
}

/**
 * Check if a given object implements the CreateCardRequest interface.
 */
export function instanceOfCreateCardRequest(value: object): value is CreateCardRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('columnId' in value) || value['columnId'] === undefined) return false;
    return true;
}

export function CreateCardRequestFromJSON(json: any): CreateCardRequest {
    return CreateCardRequestFromJSONTyped(json, false);
}

export function CreateCardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'assignedToId': json['assignedToId'] == null ? undefined : json['assignedToId'],
        'columnId': json['columnId'],
    };
}

export function CreateCardRequestToJSON(json: any): CreateCardRequest {
    return CreateCardRequestToJSONTyped(json, false);
}

export function CreateCardRequestToJSONTyped(value?: CreateCardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'assignedToId': value['assignedToId'],
        'columnId': value['columnId'],
    };
}

