/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * Kanban Board API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateProjectRequestColumnsInner } from './CreateProjectRequestColumnsInner';
import {
    CreateProjectRequestColumnsInnerFromJSON,
    CreateProjectRequestColumnsInnerFromJSONTyped,
    CreateProjectRequestColumnsInnerToJSON,
    CreateProjectRequestColumnsInnerToJSONTyped,
} from './CreateProjectRequestColumnsInner';

/**
 * 
 * @export
 * @interface CreateProjectRequest
 */
export interface CreateProjectRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateProjectRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProjectRequest
     */
    description: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateProjectRequest
     */
    members: Array<number>;
    /**
     * 
     * @type {Array<CreateProjectRequestColumnsInner>}
     * @memberof CreateProjectRequest
     */
    columns?: Array<CreateProjectRequestColumnsInner>;
}

/**
 * Check if a given object implements the CreateProjectRequest interface.
 */
export function instanceOfCreateProjectRequest(value: object): value is CreateProjectRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('members' in value) || value['members'] === undefined) return false;
    return true;
}

export function CreateProjectRequestFromJSON(json: any): CreateProjectRequest {
    return CreateProjectRequestFromJSONTyped(json, false);
}

export function CreateProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'description': json['description'],
        'members': json['members'],
        'columns': json['columns'] == null ? undefined : ((json['columns'] as Array<any>).map(CreateProjectRequestColumnsInnerFromJSON)),
    };
}

export function CreateProjectRequestToJSON(json: any): CreateProjectRequest {
    return CreateProjectRequestToJSONTyped(json, false);
}

export function CreateProjectRequestToJSONTyped(value?: CreateProjectRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'members': value['members'],
        'columns': value['columns'] == null ? undefined : ((value['columns'] as Array<any>).map(CreateProjectRequestColumnsInnerToJSON)),
    };
}

