/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * Kanban Board API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateProjectRequestColumnsInner
 */
export interface CreateProjectRequestColumnsInner {
    /**
     * 
     * @type {string}
     * @memberof CreateProjectRequestColumnsInner
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateProjectRequestColumnsInner
     */
    position?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateProjectRequestColumnsInner
     */
    projectId?: number;
}

/**
 * Check if a given object implements the CreateProjectRequestColumnsInner interface.
 */
export function instanceOfCreateProjectRequestColumnsInner(value: object): value is CreateProjectRequestColumnsInner {
    return true;
}

export function CreateProjectRequestColumnsInnerFromJSON(json: any): CreateProjectRequestColumnsInner {
    return CreateProjectRequestColumnsInnerFromJSONTyped(json, false);
}

export function CreateProjectRequestColumnsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectRequestColumnsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'position': json['position'] == null ? undefined : json['position'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
    };
}

export function CreateProjectRequestColumnsInnerToJSON(json: any): CreateProjectRequestColumnsInner {
    return CreateProjectRequestColumnsInnerToJSONTyped(json, false);
}

export function CreateProjectRequestColumnsInnerToJSONTyped(value?: CreateProjectRequestColumnsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'position': value['position'],
        'projectId': value['projectId'],
    };
}

