/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Me200Response
 */
export interface Me200Response {
    /**
     * 
     * @type {string}
     * @memberof Me200Response
     */
    username?: string;
}

/**
 * Check if a given object implements the Me200Response interface.
 */
export function instanceOfMe200Response(value: object): value is Me200Response {
    return true;
}

export function Me200ResponseFromJSON(json: any): Me200Response {
    return Me200ResponseFromJSONTyped(json, false);
}

export function Me200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Me200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function Me200ResponseToJSON(json: any): Me200Response {
    return Me200ResponseToJSONTyped(json, false);
}

export function Me200ResponseToJSONTyped(value?: Me200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
    };
}

