/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * Kanban Board API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
    UserToJSONTyped,
} from './User';

/**
 * 
 * @export
 * @interface ProjectResponse
 */
export interface ProjectResponse {
    /**
     * 
     * @type {number}
     * @memberof ProjectResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectResponse
     */
    description?: string;
    /**
     * 
     * @type {Array<User>}
     * @memberof ProjectResponse
     */
    members?: Array<User>;
    /**
     * 
     * @type {number}
     * @memberof ProjectResponse
     */
    cardsNumber?: number;
    /**
     * 
     * @type {User}
     * @memberof ProjectResponse
     */
    createdBy?: User;
    /**
     * 
     * @type {Date}
     * @memberof ProjectResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProjectResponse
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ProjectResponse interface.
 */
export function instanceOfProjectResponse(value: object): value is ProjectResponse {
    return true;
}

export function ProjectResponseFromJSON(json: any): ProjectResponse {
    return ProjectResponseFromJSONTyped(json, false);
}

export function ProjectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(UserFromJSON)),
        'cardsNumber': json['cardsNumber'] == null ? undefined : json['cardsNumber'],
        'createdBy': json['createdBy'] == null ? undefined : UserFromJSON(json['createdBy']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ProjectResponseToJSON(json: any): ProjectResponse {
    return ProjectResponseToJSONTyped(json, false);
}

export function ProjectResponseToJSONTyped(value?: ProjectResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'title': value['title'],
        'description': value['description'],
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(UserToJSON)),
        'cardsNumber': value['cardsNumber'],
        'createdBy': UserToJSON(value['createdBy']),
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

