/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * Kanban Board API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUsernameRequest
 */
export interface UpdateUsernameRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUsernameRequest
     */
    username?: string;
}

/**
 * Check if a given object implements the UpdateUsernameRequest interface.
 */
export function instanceOfUpdateUsernameRequest(value: object): value is UpdateUsernameRequest {
    return true;
}

export function UpdateUsernameRequestFromJSON(json: any): UpdateUsernameRequest {
    return UpdateUsernameRequestFromJSONTyped(json, false);
}

export function UpdateUsernameRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUsernameRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function UpdateUsernameRequestToJSON(json: any): UpdateUsernameRequest {
    return UpdateUsernameRequestToJSONTyped(json, false);
}

export function UpdateUsernameRequestToJSONTyped(value?: UpdateUsernameRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
    };
}

