/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * Kanban Board API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdatePersonalDataRequest
 */
export interface UpdatePersonalDataRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdatePersonalDataRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePersonalDataRequest
     */
    surname?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePersonalDataRequest
     */
    email?: string;
}

/**
 * Check if a given object implements the UpdatePersonalDataRequest interface.
 */
export function instanceOfUpdatePersonalDataRequest(value: object): value is UpdatePersonalDataRequest {
    return true;
}

export function UpdatePersonalDataRequestFromJSON(json: any): UpdatePersonalDataRequest {
    return UpdatePersonalDataRequestFromJSONTyped(json, false);
}

export function UpdatePersonalDataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePersonalDataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'surname': json['surname'] == null ? undefined : json['surname'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function UpdatePersonalDataRequestToJSON(json: any): UpdatePersonalDataRequest {
    return UpdatePersonalDataRequestToJSONTyped(json, false);
}

export function UpdatePersonalDataRequestToJSONTyped(value?: UpdatePersonalDataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'surname': value['surname'],
        'email': value['email'],
    };
}

