/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * Kanban Board API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateCardRequest
 */
export interface UpdateCardRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateCardRequest
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateCardRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateCardRequest
     */
    assignedToId?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateCardRequest
     */
    columnId?: number;
}

/**
 * Check if a given object implements the UpdateCardRequest interface.
 */
export function instanceOfUpdateCardRequest(value: object): value is UpdateCardRequest {
    return true;
}

export function UpdateCardRequestFromJSON(json: any): UpdateCardRequest {
    return UpdateCardRequestFromJSONTyped(json, false);
}

export function UpdateCardRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCardRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'assignedToId': json['assignedToId'] == null ? undefined : json['assignedToId'],
        'columnId': json['columnId'] == null ? undefined : json['columnId'],
    };
}

export function UpdateCardRequestToJSON(json: any): UpdateCardRequest {
    return UpdateCardRequestToJSONTyped(json, false);
}

export function UpdateCardRequestToJSONTyped(value?: UpdateCardRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'description': value['description'],
        'assignedToId': value['assignedToId'],
        'columnId': value['columnId'],
    };
}

