/* tslint:disable */
/* eslint-disable */
/**
 * TeamBoard API
 * Kanban Board API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateColumnRequest
 */
export interface UpdateColumnRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateColumnRequest
     */
    title?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateColumnRequest
     */
    position?: number;
}

/**
 * Check if a given object implements the UpdateColumnRequest interface.
 */
export function instanceOfUpdateColumnRequest(value: object): value is UpdateColumnRequest {
    return true;
}

export function UpdateColumnRequestFromJSON(json: any): UpdateColumnRequest {
    return UpdateColumnRequestFromJSONTyped(json, false);
}

export function UpdateColumnRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateColumnRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'position': json['position'] == null ? undefined : json['position'],
    };
}

export function UpdateColumnRequestToJSON(json: any): UpdateColumnRequest {
    return UpdateColumnRequestToJSONTyped(json, false);
}

export function UpdateColumnRequestToJSONTyped(value?: UpdateColumnRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'position': value['position'],
    };
}

